import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import { readFixtures } from '../../src/validation/fixtures.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
// Per-subject layout (Phase 4): S001 is the reference single-subject fixture set.
const FIXTURES_DIR = resolve(__dirname, '..', 'fixtures', 'S001');
const HAS_FIXTURES = existsSync(resolve(FIXTURES_DIR, 'params.json'));

// Fixtures are generated by `bash scripts/oracle/run.sh`. Skip with a message if absent.
const d = HAS_FIXTURES ? describe : describe.skip;

d('oracle fixtures load with documented shapes', () => {
  it('loads and passes cross-fixture shape validation', async () => {
    // readFixtures() calls validateFixtures() internally; it throws on any mismatch.
    const f = await readFixtures(FIXTURES_DIR);

    // Documented EEGMMIDB geometry.
    expect(f.params.n_channels).toBe(64);
    expect(f.params.fs_hz).toBe(160);
    expect(f.params.epoch.n_times).toBe(321);

    // Filter contract Phase 3 must reuse.
    expect(f.params.filter.type).toBe('FIR');
    expect(f.params.filter.taps.length).toBe(f.params.filter.numtaps);
    expect(f.params.filter.cutoff_hz).toEqual([8, 30]);

    // CSP matrix shape + 5 folds.
    expect(f.cspFilters.shape).toEqual([f.params.csp.n_components, 64]);
    expect(f.cvAccuracy.per_fold.length).toBe(f.params.cv.n_splits);
    expect(f.foldIndices.folds.length).toBe(f.params.cv.n_splits);

    // Sanity: accuracies in [0,1], mean matches.
    for (const a of f.cvAccuracy.per_fold) expect(a).toBeGreaterThanOrEqual(0);
    for (const a of f.cvAccuracy.per_fold) expect(a).toBeLessThanOrEqual(1);
    const mean = f.cvAccuracy.per_fold.reduce((s, x) => s + x, 0) / f.cvAccuracy.per_fold.length;
    expect(f.cvAccuracy.mean).toBeCloseTo(mean, 10);
  });
});
